package codebase.finetuning

import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.work.DisableCachingByDefault

/**
 * Gradle task `prepareFineTuningDataset` — EPIC FT-PIPELINE US-4.
 *
 * Assembles the fine-tuning dataset preparation file: a Modelfile section
 * (consumed by [OllamaFineTunerAdapter.buildModelfile]) + a Dataset section
 * listing the corpus globs that will be injected as continual pre-training
 * corpus (ratio ACL 2024 arXiv 2311.08545).
 *
 * The task is a thin Gradle adapter over the pure domain — it reads the DSL
 * properties, validates them, and writes a deterministic text artifact. The
 * heavy lifting (Modelfile construction, Ollama create/push) happens in
 * `fineTuneExpert` (next task in the chain).
 *
 * Inputs are sourced from the `fineTuning {}` extension via [CodebasePlugin]
 * wiring, or overridable per-task for advanced use cases.
 *
 * @see FineTuningRequest invariants — `baseModel` non-blank, `dataset` non-empty,
 *      `outputModelName` non-blank, `corpusRatio` in `[0.0, 1.0]`.
 */
@DisableCachingByDefault(because = "Dataset preparation — deterministic but cheap, no need for cache")
abstract class PrepareFineTuningDatasetTask : DefaultTask() {

    @get:Input
    abstract val baseModel: Property<String>

    @get:Input
    @get:Optional
    abstract val dataset: ListProperty<String>

    @get:Input
    @get:Optional
    abstract val corpusGlobs: ListProperty<String>

    @get:Input
    abstract val outputModelName: Property<String>

    @get:Input
    abstract val corpusRatio: Property<Double>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    init {
        group = "finetuning"
        description = "Prepares the fine-tuning dataset (Modelfile + corpus globs listing) for continual pre-training"
        baseModel.convention("")
        dataset.convention(emptyList())
        corpusGlobs.convention(emptyList())
        outputModelName.convention("")
        corpusRatio.convention(0.10)
    }

    @TaskAction
    fun executePrepare() {
        val resolvedBaseModel = baseModel.get().trim()
        val resolvedOutputName = outputModelName.get().trim()
        val resolvedDataset = dataset.get().ifEmpty { corpusGlobs.get() }
        val ratio = corpusRatio.get()

        if (resolvedBaseModel.isBlank()) {
            throw GradleException("fineTuning.baseModel must not be blank (prepareFineTuningDataset)")
        }
        if (resolvedOutputName.isBlank()) {
            throw GradleException("fineTuning.outputModelName must not be blank (prepareFineTuningDataset)")
        }
        if (resolvedDataset.isEmpty()) {
            throw GradleException(
                "fineTuning.dataset (or corpusGlobs fallback) must not be empty (prepareFineTuningDataset)"
            )
        }
        require(ratio in 0.0..1.0) {
            "fineTuning.corpusRatio must be in [0.0, 1.0], got $ratio"
        }

        val content = buildString {
            appendLine("# Fine-tuning dataset preparation — $resolvedOutputName")
            appendLine("# Generated by prepareFineTuningDataset (EPIC FT-PIPELINE US-4)")
            appendLine()
            appendLine("## Modelfile")
            appendLine("FROM $resolvedBaseModel")
            appendLine("# continual pre-training corpus ratio: $ratio")
            appendLine("# fine-tuned model: $resolvedOutputName")
            appendLine()
            appendLine("## Dataset")
            resolvedDataset.forEach { glob ->
                appendLine("- $glob")
            }
        }

        val out = outputFile.get().asFile
        out.parentFile.mkdirs()
        out.writeText(content)
        logger.lifecycle("[prepareFineTuningDataset] wrote {} ({} bytes, {} globs, ratio={})",
            out.absolutePath, out.length(), resolvedDataset.size, ratio)
    }
}